### ISSUE TITLE
How to get sentinel 2 data?

### ISSUE THREAD

**Issue by gc13141112** [minhokim93/LCZ_MSMLA#1]

**Comment by minhokim93** [comment]
Sentinel-2 data can be downloaded using the Sentinelsat API (https://sentinelsat.readthedocs.io/en/master/api_overview.html). Alternatively, the Copernicus Open Access Hub provides Sentinel-2 data to download manually (https://scihub.copernicus.eu). Google Earth Engine also provides a catalog of Sentinel-2 data as well.

**Comment by gc13141112** [comment]
Thank you for your reply. Can you share your test data, and I want to test and run this your model.

**Comment by minhokim93** [comment]
Please check your email.

**Comment by mike9589** [comment]
Can you share your data, I would like to test and run your model.the data_link is unavailable
